### ISSUE TITLE
Unable to select images in TinyMCE with Chrome 58+

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#6900]
As reported on SS Users Slack, because of this issue: https://github.com/tinymce/tinymce/issues/3611.

Applies to both TinyMCE 3 and 4, so affects SilverStripe 3.x and 4.x. We can upgrade TinyMCE for SilverStripe 4.x, but I don’t know what we can do about 3.x... I can’t work out if/how we might be able to apply the fix (apparently [this commit](https://github.com/tinymce/tinymce/commit/518a3bff9a5b5922e647db7b0b2d000d4d4c752f) is the one that fixes it).

EDIT: looks like I referenced the wrong commit, [this one](https://github.com/tinymce/tinymce/commit/19f3098f2bbd4740b4e9ac67b40c2a58201fc386) looks more likely to be the relevant one.

**Comment by kinglozzer** [comment]
For SilverStripe 3.x:

Okay, so taking a subset of the changes from the [linked commit](https://github.com/tinymce/tinymce/commit/19f3098f2bbd4740b4e9ac67b40c2a58201fc386#diff-e5490c44bb1973bd0210940a7c159866)... changing [this line](https://github.com/silverstripe/silverstripe-framework/blob/3.5.3/thirdparty/tinymce/tiny_mce_src.js#L1320) to the following seems to resolve the issue:

```js
selection.select(e);
```

I’ve only tested in Chrome 58 and Firefox 49, though. For anyone who wants to look at this, remember:

1. Framework uses the compressed version `tiny_mce.js`, not `tiny_mce_src.js` that I linked
2. As we use TinyMCE’s gzip thing, after changing the compressed version you’ll have to clear the `.gz` file from your temp directory or you’ll just keep getting old code
3. It’ll need to be tested in super old IE versions too

**Comment by silverstripesk** [comment]
hello,

is anybody working on it? Will be patch added to all 3.x versions? This is really annoying bug related to all SS installations.

**Comment by scttw** [comment]
We tested the patch above today in a bunch of browsers and had great success.  We will test in the rare browsers tomorrow and report back how we got on.

**Comment by Blueace** [comment]
> after changing the compressed version you’ll have to clear the .gz file from your temp directory or you’ll just keep getting old code

I made the modification in tiny_mce.js (compressed file), but Silverstripe always execute the "previous" version. Where is this .gz we have to delete ? I'm not able to find it :(

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/6986

**Comment by IsaacInsoll** [comment]
When can we expect 3.6.2 to be released? I've got many staff frustrated with this issue :)

**Comment by xini** [comment]
This is already in 3.6.1.

**Comment by IsaacInsoll** [comment]
We are still experiencing this problem and i'm definitely on 3.6.1 for both CMS and Framework (verified by mouseover on SS logo in backend). I've downloaded a fresh copy of 3.6.1 and line 1320 doesn't have the try {} block shown in the above commit.

**Comment by xini** [comment]
@IsaacInsoll you're right, sorry. @tractorcow, when can we expect 3.6.2? cheers

**Comment by IsaacInsoll** [comment]
@dhensby i see you published the last few releases, are you the person we nag for release timelines?

**Comment by dhensby** [comment]
@IsaacInsoll I suppose so ;)

we don't have a fixed schedule for releases and they come about as and when needed. There are a fair number of decent fixes waiting for release (https://github.com/silverstripe/silverstripe-framework/compare/3.6.1...3.6) but I'm afraid I'm away for a week from today.

If you use 3.6.x-dev as your composer constraint you'll get the fix and it's basically the same as taking a beta release at this point... I'm not *sure* but you might even be able to use `^3.6.2` and it'll take the .x-dev until the release is made

**Comment by dhensby** [comment]
I'll try to tag a beta today, to help out - but I can't do  a stable because if something breaks I leave it for someone else to clean up while I'm away, and that's just mean

**Comment by dhensby** [comment]
To follow up on this, I wasn't able to get a beta out in time, sorry :(
